(part "09031967921"
    (packageRef "09031967921")
    (interface
        (port "A1" (symbPinId 1) (portName "A1") (portType INOUT))
        (port "A2" (symbPinId 2) (portName "A2") (portType INOUT))
        (port "A3" (symbPinId 3) (portName "A3") (portType INOUT))
        (port "A4" (symbPinId 4) (portName "A4") (portType INOUT))
        (port "A5" (symbPinId 5) (portName "A5") (portType INOUT))
        (port "A6" (symbPinId 6) (portName "A6") (portType INOUT))
        (port "A7" (symbPinId 7) (portName "A7") (portType INOUT))
        (port "A8" (symbPinId 8) (portName "A8") (portType INOUT))
        (port "A9" (symbPinId 9) (portName "A9") (portType INOUT))
        (port "A10" (symbPinId 10) (portName "A10") (portType INOUT))
        (port "A11" (symbPinId 11) (portName "A11") (portType INOUT))
        (port "A12" (symbPinId 12) (portName "A12") (portType INOUT))
        (port "A13" (symbPinId 13) (portName "A13") (portType INOUT))
        (port "A14" (symbPinId 14) (portName "A14") (portType INOUT))
        (port "A15" (symbPinId 15) (portName "A15") (portType INOUT))
        (port "A16" (symbPinId 16) (portName "A16") (portType INOUT))
        (port "A17" (symbPinId 17) (portName "A17") (portType INOUT))
        (port "A18" (symbPinId 18) (portName "A18") (portType INOUT))
        (port "A19" (symbPinId 19) (portName "A19") (portType INOUT))
        (port "A20" (symbPinId 20) (portName "A20") (portType INOUT))
        (port "A21" (symbPinId 21) (portName "A21") (portType INOUT))
        (port "A22" (symbPinId 22) (portName "A22") (portType INOUT))
        (port "A23" (symbPinId 23) (portName "A23") (portType INOUT))
        (port "A24" (symbPinId 24) (portName "A24") (portType INOUT))
        (port "A25" (symbPinId 25) (portName "A25") (portType INOUT))
        (port "A26" (symbPinId 26) (portName "A26") (portType INOUT))
        (port "A27" (symbPinId 27) (portName "A27") (portType INOUT))
        (port "A28" (symbPinId 28) (portName "A28") (portType INOUT))
        (port "A29" (symbPinId 29) (portName "A29") (portType INOUT))
        (port "A30" (symbPinId 30) (portName "A30") (portType INOUT))
        (port "A31" (symbPinId 31) (portName "A31") (portType INOUT))
        (port "A32" (symbPinId 32) (portName "A32") (portType INOUT))
        (port "B1" (symbPinId 33) (portName "B1") (portType INOUT))
        (port "B2" (symbPinId 34) (portName "B2") (portType INOUT))
        (port "B3" (symbPinId 35) (portName "B3") (portType INOUT))
        (port "B4" (symbPinId 36) (portName "B4") (portType INOUT))
        (port "B5" (symbPinId 37) (portName "B5") (portType INOUT))
        (port "B6" (symbPinId 38) (portName "B6") (portType INOUT))
        (port "B7" (symbPinId 39) (portName "B7") (portType INOUT))
        (port "B8" (symbPinId 40) (portName "B8") (portType INOUT))
        (port "B9" (symbPinId 41) (portName "B9") (portType INOUT))
        (port "B10" (symbPinId 42) (portName "B10") (portType INOUT))
        (port "B11" (symbPinId 43) (portName "B11") (portType INOUT))
        (port "B12" (symbPinId 44) (portName "B12") (portType INOUT))
        (port "B13" (symbPinId 45) (portName "B13") (portType INOUT))
        (port "B14" (symbPinId 46) (portName "B14") (portType INOUT))
        (port "B15" (symbPinId 47) (portName "B15") (portType INOUT))
        (port "B16" (symbPinId 48) (portName "B16") (portType INOUT))
        (port "B17" (symbPinId 49) (portName "B17") (portType INOUT))
        (port "B18" (symbPinId 50) (portName "B18") (portType INOUT))
        (port "B19" (symbPinId 51) (portName "B19") (portType INOUT))
        (port "B20" (symbPinId 52) (portName "B20") (portType INOUT))
        (port "B21" (symbPinId 53) (portName "B21") (portType INOUT))
        (port "B22" (symbPinId 54) (portName "B22") (portType INOUT))
        (port "B23" (symbPinId 55) (portName "B23") (portType INOUT))
        (port "B24" (symbPinId 56) (portName "B24") (portType INOUT))
        (port "B25" (symbPinId 57) (portName "B25") (portType INOUT))
        (port "B26" (symbPinId 58) (portName "B26") (portType INOUT))
        (port "B27" (symbPinId 59) (portName "B27") (portType INOUT))
        (port "B28" (symbPinId 60) (portName "B28") (portType INOUT))
        (port "B29" (symbPinId 61) (portName "B29") (portType INOUT))
        (port "B30" (symbPinId 62) (portName "B30") (portType INOUT))
        (port "B31" (symbPinId 63) (portName "B31") (portType INOUT))
        (port "B32" (symbPinId 64) (portName "B32") (portType INOUT))
        (port "C1" (symbPinId 65) (portName "C1") (portType INOUT))
        (port "C2" (symbPinId 66) (portName "C2") (portType INOUT))
        (port "C3" (symbPinId 67) (portName "C3") (portType INOUT))
        (port "C4" (symbPinId 68) (portName "C4") (portType INOUT))
        (port "C5" (symbPinId 69) (portName "C5") (portType INOUT))
        (port "C6" (symbPinId 70) (portName "C6") (portType INOUT))
        (port "C7" (symbPinId 71) (portName "C7") (portType INOUT))
        (port "C8" (symbPinId 72) (portName "C8") (portType INOUT))
        (port "C9" (symbPinId 73) (portName "C9") (portType INOUT))
        (port "C10" (symbPinId 74) (portName "C10") (portType INOUT))
        (port "C11" (symbPinId 75) (portName "C11") (portType INOUT))
        (port "C12" (symbPinId 76) (portName "C12") (portType INOUT))
        (port "C13" (symbPinId 77) (portName "C13") (portType INOUT))
        (port "C14" (symbPinId 78) (portName "C14") (portType INOUT))
        (port "C15" (symbPinId 79) (portName "C15") (portType INOUT))
        (port "C16" (symbPinId 80) (portName "C16") (portType INOUT))
        (port "C17" (symbPinId 81) (portName "C17") (portType INOUT))
        (port "C18" (symbPinId 82) (portName "C18") (portType INOUT))
        (port "C19" (symbPinId 83) (portName "C19") (portType INOUT))
        (port "C20" (symbPinId 84) (portName "C20") (portType INOUT))
        (port "C21" (symbPinId 85) (portName "C21") (portType INOUT))
        (port "C22" (symbPinId 86) (portName "C22") (portType INOUT))
        (port "C23" (symbPinId 87) (portName "C23") (portType INOUT))
        (port "C24" (symbPinId 88) (portName "C24") (portType INOUT))
        (port "C25" (symbPinId 89) (portName "C25") (portType INOUT))
        (port "C26" (symbPinId 90) (portName "C26") (portType INOUT))
        (port "C27" (symbPinId 91) (portName "C27") (portType INOUT))
        (port "C28" (symbPinId 92) (portName "C28") (portType INOUT))
        (port "C29" (symbPinId 93) (portName "C29") (portType INOUT))
        (port "C30" (symbPinId 94) (portName "C30") (portType INOUT))
        (port "C31" (symbPinId 95) (portName "C31") (portType INOUT))
        (port "C32" (symbPinId 96) (portName "C32") (portType INOUT))
        (port "MH1" (symbPinId 97) (portName "MH1") (portType INOUT))
        (port "MH2" (symbPinId 98) (portName "MH2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "617-09-03-196-7921")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/HARTING/09031967921?qs=UV5Tb6pF94UxxOC3NGNzKQ%3D%3D")
    (property "Manufacturer_Name" "HARTING")
    (property "Manufacturer_Part_Number" "09031967921")
    (property "Description" "DIN C male angled, 96pin, PL3")
    (property "Datasheet_Link" "https://b2b.harting.com/files/download/PRD/PDF_DS/PDF_DS_09031200203.pdf")
    (property "symbolName1" "09031967921")
)
